name: Test Simple Action
on: workflow_dispatch

# jobs:
#   run-shared:
#     runs-on: ubuntu-latest
#     steps:
#       - uses: actions/checkout@v4

#       - name: Run my shared GitHub action
#         uses: UpsideDownST/cyber-bootstrap/.github/cyber-hardening@main
#         with:
#           aws_credentials: ${{ secrets.AWS }}   # <- ORG SECRET USED HERE

jobs:
  harden:
    runs-on: ubuntu-latest
    steps:
      - uses: UpsideDownST/cyber-bootstrap@main
        with:
          aws_credentials: ${{ secrets.AWS }}
          # run_stepsecurity: "true"
          run_canary: "true"
